#!/bin/sh

if [ -d .git ]; then
  echo "Already a git repository."
  exit
fi

git init
git commit --allow-empty -m "An absolutely empty repository created by git@github.com/pendashteh/git-empty.git :)"
